//! All task files of a project: open and queued tasks in `specs/tasks/`,
//! finished ones in `specs/tasks/done/`, and the generated `_index.md`.

use std::fs;
use std::path::{Path, PathBuf};

use crate::Error;
use crate::diag::Diagnostic;

use super::{Status, Task};

pub const TASKS_DIR: &str = "specs/tasks";
pub const DONE_DIR: &str = "done";
pub const INDEX_FILE: &str = "_index.md";
const INDEX_HEADER: &str = "<!-- generated by specdev; do not edit -->";

pub struct TaskStore {
    pub dir: PathBuf,
    pub tasks: Vec<Task>,
    pub done: Vec<Task>,
    /// Files that failed to parse. Reported as warnings; never fatal here.
    pub problems: Vec<Diagnostic>,
    /// Highest sequence number seen in any filename, parsed or not.
    max_seq: u32,
}

impl TaskStore {
    pub fn open(root: &Path) -> Result<Self, Error> {
        let dir = root.join(TASKS_DIR);
        if !dir.is_dir() {
            return Err(Error::Usage(
                "No specs/tasks/ directory found. Run `specdev init` first."
                    .to_string(),
            ));
        }
        let mut problems = Vec::new();
        let mut max_seq = 0;
        let tasks = load_dir(&dir, &mut problems, &mut max_seq)?;
        let done = load_dir(&dir.join(DONE_DIR), &mut problems, &mut max_seq)?;
        Ok(Self {
            dir,
            tasks,
            done,
            problems,
            max_seq,
        })
    }

    pub fn next_seq(&self) -> u32 {
        self.max_seq + 1
    }

    /// Find a task by full id (`0007-x`), sequence number (`7`, `0007`), or slug.
    pub fn find(&self, query: &str) -> Option<&Task> {
        let seq: Option<u32> = query.parse().ok();
        self.tasks.iter().chain(&self.done).find(|t| {
            let id = &t.front.id;
            id.to_string() == query || Some(id.seq) == seq || id.slug == query
        })
    }

    /// Open tasks in queue order: active, ready (the queue), draft, blocked.
    pub fn queue(&self) -> Vec<&Task> {
        let mut tasks: Vec<&Task> = self.tasks.iter().collect();
        tasks.sort_by_key(|t| (queue_rank(t.front.status), t.front.id.clone()));
        tasks
    }

    pub fn write_task(&self, task: &Task) -> Result<(), Error> {
        fs::write(&task.path, task.render())?;
        Ok(())
    }

    pub fn write_index(&self) -> Result<PathBuf, Error> {
        let path = self.dir.join(INDEX_FILE);
        fs::write(&path, self.render_index())?;
        Ok(path)
    }

    pub fn render_index(&self) -> String {
        let queue = self.queue();
        let in_group = |statuses: &[Status]| -> Vec<&Task> {
            queue
                .iter()
                .copied()
                .filter(|t| statuses.contains(&t.front.status))
                .collect()
        };
        let mut done: Vec<&Task> = self.done.iter().collect();
        done.extend(in_group(&[Status::Done]));
        done.sort_by_key(|t| t.front.id.clone());

        let groups = [
            ("Active", in_group(&[Status::InProgress, Status::Approval])),
            ("Queue", in_group(&[Status::Ready])),
            ("Draft", in_group(&[Status::Draft])),
            ("Blocked", in_group(&[Status::Blocked])),
            ("Done", done),
        ];

        let mut out = format!("{INDEX_HEADER}\n# Tasks\n");
        let mut any = false;
        for (name, tasks) in groups {
            if tasks.is_empty() {
                continue;
            }
            any = true;
            out.push_str(&format!("\n## {name}\n\n"));
            for t in tasks {
                out.push_str(&format!(
                    "- **{}** — {} — {}",
                    t.front.id,
                    t.position(),
                    t.title
                ));
                if let Some(source) = &t.front.source {
                    out.push_str(&format!(" ({source})"));
                }
                out.push('\n');
            }
        }
        if !any {
            out.push_str("\nNo tasks yet.\n");
        }
        out
    }
}

fn queue_rank(status: Status) -> u8 {
    match status {
        Status::InProgress | Status::Approval => 0,
        Status::Ready => 1,
        Status::Draft => 2,
        Status::Blocked => 3,
        Status::Done => 4,
    }
}

/// Parse every `*.md` in `dir` except `_`-prefixed files. Missing dir → empty.
fn load_dir(
    dir: &Path,
    problems: &mut Vec<Diagnostic>,
    max_seq: &mut u32,
) -> Result<Vec<Task>, Error> {
    if !dir.is_dir() {
        return Ok(Vec::new());
    }
    let mut paths: Vec<PathBuf> = fs::read_dir(dir)?
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| {
            p.is_file()
                && p.extension().is_some_and(|e| e == "md")
                && !p
                    .file_name()
                    .is_some_and(|n| n.to_string_lossy().starts_with('_'))
        })
        .collect();
    paths.sort();

    let mut tasks = Vec::new();
    for path in paths {
        if let Some(seq) = filename_seq(&path) {
            *max_seq = (*max_seq).max(seq);
        }
        let content = fs::read_to_string(&path)?;
        match Task::parse(&path, &content) {
            Ok(task) => {
                *max_seq = (*max_seq).max(task.front.id.seq);
                tasks.push(task);
            }
            Err(d) => problems.push(d.into_warning()),
        }
    }
    Ok(tasks)
}

/// Leading digits of a file name like `0007-x.md`.
fn filename_seq(path: &Path) -> Option<u32> {
    let name = path.file_name()?.to_string_lossy();
    let digits: String = name.chars().take_while(char::is_ascii_digit).collect();
    digits.parse().ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn task_file(id: &str, status: &str, title: &str) -> String {
        format!(
            "---\nid: {id}\nstatus: {status}\nscope: []\ncreated: 2026-10-03\n---\n# Task: {title}\n\n## Log\n\n- 2026-10-03 created: {title}\n"
        )
    }

    fn store_with(files: &[(&str, String)]) -> (TempDir, TaskStore) {
        let tmp = TempDir::new().unwrap();
        let dir = tmp.path().join(TASKS_DIR);
        fs::create_dir_all(dir.join(DONE_DIR)).unwrap();
        for (name, content) in files {
            fs::write(dir.join(name), content).unwrap();
        }
        let store = TaskStore::open(tmp.path()).unwrap();
        (tmp, store)
    }

    #[test]
    fn open_requires_tasks_dir() {
        let tmp = TempDir::new().unwrap();
        assert!(TaskStore::open(tmp.path()).is_err());
    }

    #[test]
    fn loads_tasks_and_done_and_skips_underscore_files() {
        let (_tmp, store) = store_with(&[
            ("0001-a.md", task_file("0001-a", "draft", "a")),
            ("done/0002-b.md", task_file("0002-b", "done", "b")),
            ("_index.md", "# Tasks\n".to_string()),
        ]);
        assert_eq!(store.tasks.len(), 1);
        assert_eq!(store.done.len(), 1);
        assert!(store.problems.is_empty());
        assert_eq!(store.next_seq(), 3);
    }

    #[test]
    fn broken_files_become_warnings_but_still_reserve_their_number() {
        let (_tmp, store) = store_with(&[
            ("0001-a.md", task_file("0001-a", "draft", "a")),
            ("0009-broken.md", "no frontmatter\n".to_string()),
        ]);
        assert_eq!(store.tasks.len(), 1);
        assert_eq!(store.problems.len(), 1);
        assert_eq!(store.next_seq(), 10);
    }

    #[test]
    fn find_by_id_seq_or_slug() {
        let (_tmp, store) = store_with(&[(
            "0003-scan-groups.md",
            task_file("0003-scan-groups", "draft", "s"),
        )]);
        for q in ["0003-scan-groups", "3", "0003", "scan-groups"] {
            assert!(store.find(q).is_some(), "{q}");
        }
        assert!(store.find("4").is_none());
    }

    #[test]
    fn queue_order_and_index_groups() {
        let (_tmp, store) = store_with(&[
            ("0001-d.md", task_file("0001-d", "draft", "drafted")),
            ("0002-r.md", task_file("0002-r", "ready", "queued")),
            ("0003-a.md", task_file("0003-a", "approval", "active")),
            ("done/0000-old.md", task_file("0000-old", "done", "old")),
        ]);
        let order: Vec<String> = store
            .queue()
            .iter()
            .map(|t| t.front.id.to_string())
            .collect();
        assert_eq!(order, vec!["0003-a", "0002-r", "0001-d"]);

        let index = store.render_index();
        assert!(index.starts_with(INDEX_HEADER));
        let active = index.find("## Active").unwrap();
        let queue = index.find("## Queue").unwrap();
        let draft = index.find("## Draft").unwrap();
        let done = index.find("## Done").unwrap();
        assert!(active < queue && queue < draft && draft < done);
        assert!(index.contains("- **0002-r** — ready — queued\n"));
        assert!(!index.contains("## Blocked"));
    }

    #[test]
    fn empty_index() {
        let (_tmp, store) = store_with(&[]);
        assert_eq!(
            store.render_index(),
            format!("{INDEX_HEADER}\n# Tasks\n\nNo tasks yet.\n")
        );
    }
}
